Repository googleapis/google-oauth-java-client, pull requests merged in 2020-11, with the labels that each got.

#553 chore: remove TravisCI config
  .travis.yml
Labels: cla: yes

#558 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#560 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#565 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#567 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#568 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#569 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: automerge, cla: yes, context: full, samples
