Repository googleapis/google-oauth-java-client, pull requests merged in 2020-12, with the labels that each got.

#570 deps: fix declared dependencies
  .github/workflows/ci.yaml
  google-oauth-client-appengine/pom.xml
  google-oauth-client-java6/pom.xml
  google-oauth-client-jetty/pom.xml
  google-oauth-client-servlet/pom.xml
  google-oauth-client/pom.xml
  samples/dailymotion-cmdline-sample/pom.xml
  samples/keycloak-pkce-cmdline-sample/pom.xml
Labels: cla: yes

#575 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#579 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#583 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, merge

#585 fix: don't duplicate managed versions
  google-oauth-client-jetty/pom.xml
  pom.xml
Labels: cla: yes
