Repository googleapis/google-oauth-java-client, pull requests merged in 2020-09, with the labels that each got.

#501 Fix typos
  samples/dailymotion-cmdline-sample/README.md
Labels: cla: yes

#502 replace deprecated constructor
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthParameters.java
Labels: cla: yes

#498 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#505 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#506 chore: add settings sync, cleanup CODEOWNERS
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
  .repo-metadata.json
Labels: cla: yes

#534 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
