Repository googleapis/google-oauth-java-client, pull requests merged in 2021-01, with the labels that each got.

#589 remove Eclipse files
  samples/dailymotion-cmdline-sample/.classpath
  samples/dailymotion-cmdline-sample/.project
  samples/dailymotion-cmdline-sample/.settings/org.eclipse.jdt.core.prefs
  samples/dailymotion-cmdline-sample/.settings/org.eclipse.jdt.ui.prefs
  samples/dailymotion-cmdline-sample/DailyMotionSample.launch
  samples/dailymotion-cmdline-sample/README.md
Labels: cla: yes

#586 fix: switch to GSON per security team advice
  google-oauth-client-appengine/src/main/java/com/google/api/client/extensions/appengine/auth/AbstractAppEngineCallbackServlet.java
  google-oauth-client-appengine/src/main/java/com/google/api/client/extensions/appengine/auth/AbstractAppEngineFlowServlet.java
  google-oauth-client-appengine/src/main/java/com/google/api/client/extensions/appengine/auth/oauth2/AbstractAppEngineAuthorizationCodeCallbackServlet.java
  google-oauth-client-appengine/src/main/java/com/google/api/client/extensions/appengine/auth/oauth2/AbstractAppEngineAuthorizationCodeServlet.java
  google-oauth-client-java6/pom.xml
  google-oauth-client-java6/src/test/java/com/google/api/client/extensions/java6/auth/oauth2/FileCredentialStoreTest.java
  google-oauth-client-servlet/src/main/java/com/google/api/client/extensions/servlet/auth/AbstractCallbackServlet.java
  google-oauth-client-servlet/src/main/java/com/google/api/client/extensions/servlet/auth/AbstractFlowUserServlet.java
  google-oauth-client-servlet/src/main/java/com/google/api/client/extensions/servlet/auth/oauth2/AbstractAuthorizationCodeCallbackServlet.java
  google-oauth-client-servlet/src/main/java/com/google/api/client/extensions/servlet/auth/oauth2/AbstractAuthorizationCodeServlet.java
  google-oauth-client/pom.xml
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/AuthorizationCodeTokenRequest.java
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/ClientCredentialsTokenRequest.java
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/ClientParametersAuthentication.java
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/PasswordTokenRequest.java
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/RefreshTokenRequest.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/AuthenticationTestBase.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/AuthorizationCodeFlowTest.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/CustomTokenRequestTest.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/CustomTokenResponseTest.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenErrorResponseTest.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenRequestTest.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenResponseTest.java
  samples/dailymotion-cmdline-sample/pom.xml
  samples/dailymotion-cmdline-sample/src/main/java/com/google/api/services/samples/dailymotion/cmdline/DailyMotionSample.java
  samples/keycloak-pkce-cmdline-sample/pom.xml
  samples/keycloak-pkce-cmdline-sample/src/main/java/com/google/api/services/samples/keycloak/cmdline/PKCESample.java
  samples/snippets/pom.xml
Labels: cla: yes

#595 fix: don't swallow exceptions in LocalServerReceiver
  google-oauth-client-jetty/pom.xml
  google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java
  google-oauth-client-jetty/src/test/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiverTest.java
Labels: cla: yes

#604 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#606 build: migrate to flakybot
  .kokoro/build.sh
Labels: automerge, cla: yes
