Repository googleapis/google-oauth-java-client, pull requests merged in 2021-05, with the labels that each got.

#671 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#673 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#676 build: configure branch 1.31.4-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#677 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: cla: yes

#672 fix: remove codecov
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/presubmit/common.cfg
  codecov.yaml
  synth.metadata
Labels: cla: yes

#689 chore: Re-generated to pick up changes from synthtool
  .kokoro/build.sh
  .kokoro/presubmit/common.cfg
  .kokoro/release/publish_javadoc11.sh
  codecov.yaml
  synth.metadata
Labels: cla: yes, context: partial

#687 chore: update cloud-rad doclet
  pom.xml
Labels: cla: yes

#690 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#691 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
