Repository googleapis/google-oauth-java-client, pull requests merged in 2021-03, with the labels that each got.

#641 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#649 chore: remove required Kokoro checks
  .github/sync-repo-settings.yaml
Labels: cla: yes

#646 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: full, kokoro:force-run

#640 test: add tests for scopes field in TokenRequest
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenRequestTest.java
Labels: cla: yes

#650 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full
