Repository googleapis/google-oauth-java-client, pull requests merged in 2021-09, with the labels that each got.

#748 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, automerge

#751 chore: update java docfx doclet version
  pom.xml
Labels: kokoro:force-run, cla: yes

#750 chore(java): update shared-config and shared-dependencies version in pom template
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#749 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, context: none

#753 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, automerge

#754 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes

#758 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  README.md
Labels: cla: yes, automerge
