Repository googleapis/google-oauth-java-client, pull requests merged in 2021-11, with the labels that each got.

#768 fix: new java format dependencies and linter fix
  .github/.OwlBot.lock.yaml
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/release/publish_javadoc11.sh
  pom.xml
Labels: cla: yes, automerge

#772 feat: next release from main branch is 1.33.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#773 ci: configure the protected branch
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
Labels: cla: yes

#770 chore: cleanup cloud RAD generation
  pom.xml
Labels: cla: yes, automerge

#743 chore: Added throws clause Fixes #598
  google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/AuthorizationCodeInstalledApp.java
  google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/FileCredentialStore.java
  google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/VerificationCodeReceiver.java
Labels: kokoro:force-run, cla: yes

#776 chore: remove wrong and ineffective dependencies
  pom.xml
Labels: cla: yes, automerge
