Repository googleapis/google-oauth-java-client, pull requests merged in 2021-08, with the labels that each got.

#713 fix: Revert "chore(deps): update dependency com.google.googlejavaformat:google-java-format to v1.10.0" to fix linter
  google-oauth-client-bom/pom.xml
  pom.xml
Labels: cla: yes

#711 feat: Add HMAC-SHA256 signature method for OAuth 1.0
  google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthHmacSha256Signer.java
  google-oauth-client/src/test/java/com/google/api/client/auth/oauth/OAuthHmacSha256SignerTest.java
Labels: cla: yes

#715 build: migrate to new google endpoint on sonatype
  google-oauth-client-bom/pom.xml
Labels: cla: yes

#721 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: kokoro:force-run, cla: yes, automerge, context: full

#726 chore: update doclet version
  pom.xml
Labels: cla: yes

#728 fix: fix release
  pom.xml
Labels: cla: yes

#734 chore: fix migration to sonatype endpoint
  google-oauth-client-bom/pom.xml
Labels: cla: yes, automerge
