Repository googleapis/google-oauth-java-client, pull requests merged in 2025-01, with the labels that each got.

#1134 fix: javadoc fix in IdTokenVerifier
  google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java
Labels: size: xs

#1135 ci: Airlock-friendly build dependencies
  pom.xml
  samples/dailymotion-cmdline-sample/pom.xml
  samples/keycloak-pkce-cmdline-sample/pom.xml
  samples/pom.xml
Labels: size: m

#1142 chore: fix broken link for javadoc.
  google-oauth-client-appengine/pom.xml
  google-oauth-client-java6/pom.xml
  google-oauth-client-jetty/pom.xml
  google-oauth-client-servlet/pom.xml
  google-oauth-client/pom.xml
  pom.xml
Labels: size: s

#1140 deps: newer Maven plugin versions for Airlock
  .github/workflows/ci.yaml
  checkstyle.xml
  google-oauth-client-assembly/assembly.xml
  pom.xml
  samples/checkstyle.xml
  samples/dailymotion-cmdline-sample/pom.xml
  samples/keycloak-pkce-cmdline-sample/pom.xml
Labels: size: m

#1144 chore: checkstyle-test profile name change
  pom.xml
  samples/dailymotion-cmdline-sample/pom.xml
  samples/keycloak-pkce-cmdline-sample/pom.xml
Labels: size: xs

#1145 fix: animal-sniffer and clirr to a profiles
  google-oauth-client-appengine/pom.xml
  google-oauth-client-java6/pom.xml
  google-oauth-client-jetty/pom.xml
  pom.xml
Labels: size: m
